# 定义编译器
CXX = g++

# 定义编译器标志
CXXFLAGS = -Wall -std=c++11

# 定义目标可执行文件
TARGET = demo

# 定义源文件
SRCS = main.cpp Table.cpp Structs.cpp

# 默认目标
all: $(TARGET)

# 构建目标可执行文件
$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRCS)

# 清理目标
clean:
	rm -f $(TARGET)

# 伪目标
.PHONY: all clean
